name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  check-documentation:
    name: Check the documentation
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Markdown linter
        run: npm install --global markdownlint-cli
      - name: Check Markdown files
        run: markdownlint *.md
